OSMCha/osmcha-frontend

package.json
src/assets/index.css
src/components/changeset/user.js

I would like to disallow images to be rendered. I tested to add {disallowedTypes: ['Image']} to the markdown renderer, but it didn't work.

render markdown in user description

---

src/components/changeset/open_in.js

Https in JOSM is unreliable and will be dropped soon. See https://josm.openstreetmap.de/ticket/10033
All modern browsers support calling 127.0.0.1 over http even from https pages, per spec:
https://github.com/w3c/webappsec-mixed-content/commit/349501cdaa4b4dc1e2a8aacb216ced58fd316165
https://w3c.github.io/webappsec-secure-contexts/#is-origin-trustworthy
JOSM's default behaviour is to run without https.
Openstreetmap.org itself also always calls JOSM over http.

Always call JOSM over http

---

README.md

The Changeset viewer was missing on the list of related repositories.
I also moved this list up, so one can find it more easily.
This is a follow up to https://github.com/mapbox/osmcha-frontend/pull/358 and related to https://github.com/mapbox/osmcha-frontend/issues/356.

Improve repository list in readme.

---

public/index.html

This should prevent google translate to randomly pop up without being actually visible on mobile. This should not influence the translate button which links to google translate externally https://github.com/h5bp/html5-boilerplate/commit/6d10fc8ccecbcfedbc743d7431688562cd6ae47a#diff-65730bf0f1b9dc6e703f19456334bd0fR567
- I open https://osmcha.mapbox.com/changesets/74764009/ from the rss feed inside a iOS integrated browser (iOS in German)
- I tab and touble tab the map a bit to reach some elements
- It might be, that is only happens on the to left area of the screen, but I did not evaluate this enough
- Suddenly and without seeing a translate-UI first, the google translate UI loads for strings like https://translate.google.com/#auto/en/siehe%20Änderungssatz%3A%2074722824

Add meta tag to prevent google translate

---

ABOUT.md

Under the section of `Other tools for validation`, updated broken links and removed reference to OSM comments API (now deprecated).

Update broken links in About doc

---

src/components/changeset/features.js

JOSM allows user to set whether they would like remote control to create new layers or not in preferences. 
In OSMCha, by specifying `new_layer=true` in the remote control URL, the user preference is bypassed.
I think it would be best to use the default set in JOSM. Another solution would be provide two remote control links, one creating a new layer, one which does not.

Use user preference for opening new layers in JOSM

---

ABOUT.md

This changed a while ago, eg in https://github.com/mapbox/osmcha-frontend/issues/293.

Update about.md: Login is required

---

src/components/changeset/open_in.js

In the case someone setup "Modify" button in web interface to open
something different than iD (JOSM, …) "Open with -> id" would not open
iD.
Passing editor=id parameter to url forces to actually use iD editor.

Make buttion "Open with -> iD" opens with iD in all cases

---

README.md

The given URL redirects to mapbox.com, so this is not working ATM. Since it seems to not be used ATM, we should at least hint that it is non-working for now. This is what this PR is about.
```console
$ http https://mapbox.github.io
HTTP/1.1 200 OK
Accept-Ranges: bytes
Access-Control-Allow-Origin: *
Age: 0
Cache-Control: max-age=600
Connection: keep-alive
Content-Length: 117
Content-Type: text/html; charset=utf-8
Date: Sat, 11 Apr 2020 06:09:50 GMT
ETag: "52e957f2-75"
Expires: Sat, 11 Apr 2020 06:19:50 GMT
Last-Modified: Wed, 29 Jan 2014 19:35:14 GMT
Server: GitHub.com
Vary: Accept-Encoding
Via: 1.1 varnish
X-Cache: MISS
X-Cache-Hits: 0
X-Fastly-Request-ID: 3e2512beb6b85f8088cd2c9f2531ca8eb97a09d6
X-GitHub-Request-Id: B6E2:2176:1015E7:149519:5E915F2D
X-Proxy-Cache: MISS
X-Served-By: …
```

readme: hint that the deploy:dev does not work

---

README.md
public/local-landing.html
src/components/changeset/sign_in_button.js
src/views/navbar_sidebar.js

The main changes are:
- pass the oauth_token to the local-landing.html (as a hash, since this was easiest)
- extend the local-landing with the tutorial that was in the readme previously and provide a link that uses the given oauth_token
- cleanup readme, since the UI explains itself now
Also:
- remove a non-needed if-statement
- add a link to the readme

Login on dev simplified

---

public/index.html

This is bad for SEO, but since SEO is not of our concern(*), we can just do the redirect in JS. This follows the pattern for the non-http-redirect right above.
(*) With Google Webmaster Tools it would also be possible to specify a primary domain to solve the duplicate content problem.
This solves https://github.com/mapbox/osmcha-frontend/issues/441
This script is based on https://stackoverflow.com/a/47281530

Redirect to non-www via JS

---

src/components/changeset/open_in.js
src/components/changeset/user.js
src/views/navbar_changeset.js

https://openstreetmap.org HTTP 301 redirects to https://www.openstreetmap.org.
This PR directly https://uses www.openstreetmap.org to avoid a redirect. 
It also allows copying OSM changesets URL from osmcha to the File>Open Location dialog of JOSM, as it doesn't accept non-www-prefixed OSM urls.

Prepend www to openstreetmap.org hostnames

---

src/views/navbar_sidebar.js

Remove the 10-character limit on the username button on the sidebar.
_Then_
_Now_

Remove 10-character limit on the username sidebar button

---

package.json
src/components/filters/location.js
yarn.lock

Resolves #419 and update Turf JS libraries

Improve location filter with debounce and a better geom simplification

---

src/components/filters/filters_list.js
src/config/filters.json

Contributes to #344
Related to https://github.com/willemarcel/osmcha-django/pull/597 & https://github.com/mapbox/osm-adiff-watchbot/pull/65

Add tag_changes field to Filters

---

package.json
src/views/about.js
yarn.lock

We received a new HackerOne report for [repo](https://github.com/mapbox/osmcha-frontend/). 
This report is about using “React’s dangerously set inner HTML.”
Recomendations: sanitize data when using dangerouslySetInnerHTML, which means changing line #93 from `__html: this.state.about` to `__html: sanitize(this.state.about)`.

Add sanitize to DangerouslySetInnerHTML

---

src/components/changeset/open_in.js

The domain for Rapid has changed from mapwith.ai to rapideditor.org

Update url for Rapid

---

.github/workflows/docker-publish.yaml
Dockerfile
package.json

Builds and publishes an nginx image with the OSMCha frontend application to GHCR. Images are tagged by commit ids. We publish separate images - one for production (ghcr.io/osmcha/osmcha-frontend) and one for the test instance (ghcr.io/osmcha/osmcha-frontend-test) for now.

Dockerfile to serve the frontend through nginx

---

src/components/changeset/discussions.js
src/components/changeset/header.js
src/components/changeset/user.js
src/components/list/title.js
src/components/relative_time.js

This is a small PR which adds title text (which desktop browsers show on hover) to relative timestamps in the UI, showing the absolute time. This is helpful when the UI shows things like "2 years ago" but you want to know the specific day that the change was made.
Example when hovering over a changeset timestamp:
I added a new `RelativeTime` component to contain this bit of logic, and changed everywhere that displays relative times to use this component.
This is my first PR to this project. I ran `yarn precommit` to lint and format the changes, but let me know if there are style changes I should make.
P.S. I attempted to follow the instructions in the README about local development, but they seem slightly out of date. I needed to do two things before I was able to test my changes locally: …

Add full timestamps when hovering over relative times (e.g. "3 months ago")

---

src/components/filters/location.js

This is the first attempt at fixing problems with location search when Chinese or other similar languages are used. Please see commit messages for details.
Related issue is: https://github.com/mapbox/osmcha-frontend/issues/538
Tested manually on both Firefox and Brave. It looks like the used select component has more strange issues. Was not able to fix those but also checked that I didn't create more issues. The react-select version is quite old: `^1.0.0-rc.5` in `package.json` while latest release is 5.7.3.

Enable using location search with shorter place names

---

CODE-OF-CONDUCT.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md

Since OSMCha is an [OpenStreetMap US Charter Project](https://openstreetmap.us/news/2024/03/OSMCha-new-home/), it follows the [OSM US Code of Conduct](https://wiki.openstreetmap.org/wiki/Foundation/Local_Chapters/United_States/Code_of_Conduct_Committee/OSM_US_Code_of_Conduct).
This PR removes the obsolete link to the Mapbox Code of Conduct that previously applied to this project, and adds a link to the OSM US Code of Conduct in its place.

Replace Mapbox Code of Conduct with OSM US one

---

README.md
circle.yml

This project isn't built using CircleCI anymore; CI builds now use [Github Actions](https://github.com/OSMCha/osmcha-frontend/actions).

Remove CircleCI badge from README.md

---

.github/workflows/docker-publish.yaml

This should fix the build failure introduced in #749. It also bumps the versions of various actions and adds labels to container images to match any semver tags (a git tag `v1.2.3` creates an image labeled `osmcha/osmcha-frontend:1.2.3`).

Remove test image from GitHub Actions workflow

---

src/components/changeset/tag_changes.js

Add dir='auto' to tag values in Tag Changes view to correctly display RTL text

---

src/components/relative_time.js
src/store/changesets_page_actions.js

This PR fixes a bug in the paginator widget where the prev/next arrows did not work after initial page load, and would only start working once you clicked on a specific page number (e.g '2'). Turns out this was due to some accidental `[]` in a Redux selector which was causing certain code paths to turn `pageIndex` into an array instead of a number.
It also fixes an unrelated console warning from React

Fix bug preventing paginator from working on first load

---

package.json
src/components/element_info.js
yarn.lock

Relation membership order is semantically significant in some types of relations (e.g. route relations), so this change ensures that the original order is preserved when listing members in the element info panel (previously they were shown sorted by element ID).

Preserve order of relation members in element info table

---

src/components/element_info.js

Fixes #789
The additional `<span>` elements inside the `<td>` elements are necessary to make the table render in the desired layout. In an RTL context, the `::before` pseudo-element comes at the right, so if the `td` itself were RTL then the `=` sign separating the key and value would instead come at the very end (right side) of the table row.

Fix display of RTL tag and role values in element info table

---

src/views/map.js

Fixes #795.
If the user is not logged in, `initializeMap()` will now do nothing. This prevents it from attempting to attach a MapLibre map to a container element that does not exist, which throws an uncaught error and results in the entire page becoming blank.

Fix blank page when loading a changeset while not logged in

---

public/index.html

OSMCha is spending almost the entire plausible tracking quota paid by DevSeed, so we need to remove it, unfortunately.

Remove plausible analytics

---

src/components/changeset/map_options.js
src/views/map.js

Resolves #764
Esri's [permitted uses statement](https://www.arcgis.com/home/item.html?id=8e90a00a0a6845a49262e0b756f57a10) for their imagery products allows us to use their imagery in OSMCha (emphasis mine):
> Esri and its imagery contributors grant Users the non-exclusive right to use the World Imagery map to trace features and **validate edits** in the creation of vector data. Users that create vector data from the World Imagery map can publicly share that vector data through a GIS data clearinghouse of their own or through another open data site. Public sharing can also be achieved through ArcGIS Open Data or the OpenStreetMap (OSM) Initiative. For ArcGIS users that want to contribute such vector data to OSM, Esri provides applications and services directly accessible from ArcGIS …

Add Esri imagery basemap sources

---

package.json
src/components/element_info.js
src/components/tag_value.js
src/components/tag_value.test.js
yarn.lock

Any tag supported by [JOSM/tag2link](https://github.com/JOSM/tag2link) is now rendered as a clickable link in the tag diff, such as `*:wikidata`, `website`, `contact:twitter`, `gnis:feature_id`, and many more.
This functionality was previously available in [changeset-map](https://github.com/osmlab/changeset-map) for a limited subset of keys.
---
create:
edit:
delete:
unchanged:
Closes #630

make links & foreign keys clickable in the tag diff
