.eslintrc
.flowconfig
README.md
package.json
src/app.js
src/index.js
src/store/index.js
src/store/user_actions.js
src/store/user_reducer.js
src/utils/safeStorage.js
src/utils/safe_storage.js
yarn.lock

Following the same patterns from [to-fix](github.com/osmlab/to-fix).
cc: @kepta @batpad

[wip] Setup redux

---

circle.yml
package.json
src/app.test.js

- gets the test running fine.
- jest needs node > 7.
@ajithranka

circle yml

---

package.json
src/app.js
src/index.js
src/store/index.js
yarn.lock

Adds [react-router](https://github.com/ReactTraining/react-router) and  [react-router-redux](https://github.com/ReactTraining/react-router/tree/master/packages/react-router-redux)

Redux router

---

package.json
public/index.html
src/app.js
src/components/Navbar.js
src/index.js
yarn.lock

- Adds assembly to the project.
- Adds library [`classNames`](https://www.google.co.in/webhp?sourceid=chrome-instant&rlz=1C5CHFA_enIN726IN726&ion=1&espv=2&ie=UTF-8#q=react+classnames). Really helps in taming the lengthy css class names we are gonna use.
- Dummy navbar to try it out.
😄 
cc @ajithranka

Assembly style

---

src/store/index.js
src/utils/safe_storage.js

- Improved consistency with `Window.localStorage` API
- Removed seralization/de-serialization of values (this should be the user's responsibility)
- Improved type annotations
cc: @kepta

Safe storage

---

src/components/changeset/box.js
src/components/changeset/details.js
src/components/changeset/discussions.js
src/components/changeset/features.js
src/components/changeset/header.js
src/components/changeset/index.js
src/components/create_delete_modify.js
src/components/reasons.js
src/config/config_development.js
src/config/config_production.js
src/config/constants.js
src/css/index.css

cc: @geohacker @batpad @rasagy @kepta

Styling for changeset details page

---

src/components/changeset/features.js
src/components/changeset/index.js

*Changeset ID: 48961500*
The styling for multiple reasons can be improved. cc: @rasagy @tridip1931 
cc: @kepta

Read suspicious features from changeset properties

---

src/components/list/row.js
src/components/reasons.js
src/css/index.css

Fixed border left and changed some class names.
cc: @ajithranka @rasagy @kepta

Changeset list border fix

---

ABOUT.md

cc @kepta @rasagy @manoharuss @batpad @jinalfoflia

minor copy edits

---

src/components/changeset/user.js

more copy edits

---

ABOUT.md

cc @kepta @jinalfoflia @geohacker

Added screenshots and more shortcuts

---

src/components/changeset/features.js

Consistent blue for reasons

---

ABOUT.md

Updated screenshots, added commas in sentences where necessary and missing. Format changes.
cc @kepta @jinalfoflia @geohacker

Updated screenshots,commas,formatting

---

.flowconfig
package-lock.json
package.json
src/components/changeset/user.js
src/store/changeset_actions.js
src/utils/routing.js
src/views/about.js
src/views/navbar_sidebar.js

fixes #117 
fixes #109
fixed #104
cc @ajithranka

Fix location

---

package.json
src/components/bbox_picker.js
src/components/changeset/index.js
src/components/changeset/user.js
src/config/bindings.js
src/config/filters.json
src/network/changesets_page.js
src/network/openstreetmap.js
src/store/changeset_actions.js
src/views/__snapshots__/filters.test.js.snap
src/views/changeset.js
src/views/filters.js
yarn.lock

Fixes #126 
Fixes #120 
Fixes #119 
Fixes #115 
Fixes #68

Stats and friends

---

src/components/avatar.js
src/components/changeset/user.js
src/views/navbar_sidebar.js

Fixes #131.
cc: @kepta @rasagy

User avatar styling

---

src/components/changeset/user.js
src/config/constants.js

Ref #111.
cc: @batpad @kepta @rasagy

Show past OSM usernames

---

package.json
public/404.html
public/index.html

Force redirect to https, fixes #140

---

src/config/filters.json

Fix order by bug

---

package.json
src/components/changeset/control_layout.js
src/components/changeset/index.js
src/components/changeset/user.js
src/components/fetch_data_enhancer.js
src/components/keyboard_enhancer.js
src/components/list/footer.js
src/components/list/index.js
src/components/loading_enhancer.js
src/config/bindings.js
src/index.js
src/utils/component.js
src/utils/promise.js
src/views/changeset.js
src/views/changesets_list.js
src/views/navbar_changeset.js
yarn.lock

use HOCs for keyboard shortcuts and data fetching

---

package.json
src/components/filters/date.js
src/components/filters/index.js
src/views/filters.js
yarn.lock

Replace native date input with react-datepicker

---

src/components/customURL.js
src/views/user.js

/cc: @kepta 
Please check this.

Added rss link button.

---

src/views/user.js

Modified hardcoded URL

---

src/components/changeset/open_in.js

Added url query parameter for level 0. 
(closes #179)
@kepta Please review this.

Add level 0 object

---

src/components/changeset/header.js

(closes #156)
@kepta Please review this.

Added text direction

---

src/config/notifications.js

Related to https://github.com/mapbox/osmcha-frontend/issues/144

use 'sign in' instead of 'login' in messages

---

src/components/filters/filters_list.js
src/config/filters.json

move 'BBox size bound' to the 'Basic' section and improve the description

---

src/config/constants.js

@kepta - this points to a newer overpass instance because we deprecated the previous one. Can you merge + deploy? Thank you.
cc @batpad

switch overpass instance

---

ABOUT.md
src/components/changeset/user.js

Missingmaps

---

src/components/changeset/details.js

#84 
@willemarcel please review this

changed regex

---

package.json
src/assets/index.css
src/components/bbox_picker.js
src/components/changeset/details.js
src/components/filters/filters_list.js
src/components/filters/index.js
src/components/filters/location.js
src/components/filters/wrapper.js
src/components/list/index.test.js
src/components/list/row.test.js
src/config/constants.js
src/config/filters.json
src/index.js
src/network/aoi.js
src/network/changesets_page.js
src/network/nominatim.js
src/store/aoi_actions.js
src/views/filters._test.js
yarn.lock

Solves https://github.com/mapbox/osmcha-frontend/issues/208 and https://github.com/mapbox/osmcha-frontend/issues/133

add Location field

---

src/components/changeset/comment.js
src/components/changeset/discussions.js
src/components/user/details.js
src/views/user.js

UI enhancement on review comments.

---

ABOUT.md
CHANGELOG.md
package.json
src/components/changeset/comment.js

Update docs + avoid post comment error and success msgs to be shown at same time

---

ABOUT.md
CHANGELOG.md
package.json
src/network/changesets_page.js
src/store/aoi_actions.js
src/store/changesets_page_actions.js
src/store/filters_actions.js
src/views/changesets_list.js
src/views/filters.js

* Fix filters that have search params larger than supported by the server. Solves (#274)
* Removed to-fix link 
* Fix error when clearing date__gte filter field (#266)

v0.42.0 - several updates

---

CHANGELOG.md
package.json
src/assets/index.css
src/components/filters/filters_header.js

Add "My Filters" dropdown to filters page

---

src/components/list/header.js

As suggested by @rasagy... :1st_place_medal:

show number of active filter fields on Filter button

---

CHANGELOG.md
README.md
package.json
src/assets/index.css
src/components/changeset/features.js
src/components/changeset/index.js
src/components/reasons.js
src/config/constants.js
src/utils/promise.js
src/views/changeset.js

Show the feature's note when the mouse is over a reason

---

CHANGELOG.md
package.json
src/app.js
src/assets/index.css
src/components/filters/filters_list.js
src/components/user/block_markup.js
src/components/user/save_user.js
src/config/filters.json
src/views/navbar_sidebar.js
src/views/saved_filters.js
src/views/trusted_users.js
src/views/user.js
src/views/watchlist.js

- Add watchlist filter
- Separate Saved Filters, Watchlist and Trusted Users in different views
- Replace the user button by a dropdown menu

0.54.0 release

---

CONTRIBUTING.md
README.md

This is based on https://github.com/mapbox/osmcha-frontend/issues/356#issuecomment-495827278.
Closes #356

Update installation instructions

---

package.json
src/components/filters/multi_select.js
src/config/constants.js
src/config/filters.json
src/store/auth_actions.js
src/store/changesets_page_actions.js
yarn.lock

* Exclude changesets newer than 5 minutes from query results
* Change position of status notification
* Show unverified teams and add string to distinct the verified ones on the filters page

0.58.0 release

---

package.json
src/config/constants.js
src/store/changesets_page_actions.js
src/utils/filters.js

Change way to filter out changesets newer than 5 minutes.

0.58.2 release

---

CHANGELOG.md
package.json
src/components/changeset/header.js
src/network/aoi.js
src/store/auth_actions.js

- disable logout when requests fails 
- adjust status modal position

v0.60.0 release

---

src/components/changeset/open_in.js

Issue: Remove OSM-HV link #382

remove link to OSM-HV from the Open with menu

---

src/components/changeset/features.js
src/views/teams.js

fix new team form disabled error

fix bug when creating new teams

---

src/components/changeset/comment.js
src/components/changeset/details.js
src/components/changeset/discussions.js
src/components/changeset/features.js
src/components/changeset/header.js
src/components/changeset/tag_changes.js
src/components/filters/wrapper.js
src/components/list/title.js
src/components/user/details.js
src/views/edit_team.js
src/views/navbar_changeset.js
src/views/navbar_sidebar.js
src/views/saved_filters.js
src/views/teams.js
src/views/user.js

Cleanup strong tags

---

src/components/changeset/map_options.js
src/store/index.js
src/store/map_controls_actions.js
src/store/map_controls_reducer.js
src/views/map.js

Resolves https://github.com/mapbox/osmcha-frontend/issues/268

Enable OSM Carto style + replace radio buttons by dropdown

---

src/components/changeset/geometry_changes.js
src/components/changeset/other_features.js
src/components/changeset/tag_changes.js
src/components/expand_item_icon.js
src/components/open_all.js

- Solve bug when switching from one changeset to another cached one
- Convert from Class to Function and make use of Hooks
- Refactor repeated components
- Improve Open all / Close all button

Refactor TagChanges, GeometryChanges and OtherFeatures components

---

ABOUT.md
src/components/changeset/features.js
src/components/changeset/geometry_changes.js
src/components/changeset/other_features.js
src/components/changeset/tag_changes.js
src/components/open_all.js
src/config/bindings.js

- Disable space as shortcut to navigate between changesets
- Update shortcuts documentation

Navigate between features with keyboard shortcuts ('tab')

---

src/components/changeset/discussions.js

Fix date parsing on the Discussions tab

---

src/components/changeset/details.js
src/components/changeset/property.js
src/components/changeset/property_list.js

Show additional changeset's metadata information

---

src/views/navbar_sidebar.js

Add My Changesets and My Reviews links to the user menu

---

src/views/navbar_changeset.js

Handle better the space in Changeset Dropdown in mobile screens

---

CHANGELOG.md
package.json
src/config/filters.json
yarn.lock

Resolves https://github.com/mapbox/osmcha-frontend/issues/623

Add ANY and ALL options to tag_changes filter field

---

src/config/filters.json
src/views/teams.js

Improve text on teams and filters pages

---

package.json
src/components/dropdown.js
src/index.js

Keep Tags dropdown open + update analytics code

---

src/views/navbar_sidebar.js

Resolves #668 and removes unneeded props of the `NavbarSidebar` component.

Change search param used in My Changesets query

---

src/components/changeset/open_in.js

Add support for osm-revert

---

src/components/changeset/tags.js
src/config/filters.json

Remove order by id options + fix Tags dropdown loading

---

CHANGELOG.md
package.json
src/components/filters/multi_select.js
src/network/mapping_team.js

Fix error in Filter multiselects

---

src/components/changeset/open_in.js

As explained in #600, it would be nice for this option to only show up for changesets from the past month
Closes #688, closes #600

Add support for Pascal Neis' Changeset Visualization app

---

CHANGELOG.md
package.json

Update package.json version field and add changelog entry

Bump version to 1.1.0

---

src/components/filters/location.js
src/views/filters.js

Resolves #774 (polygon draw mode has been added back) and #776 (draw modes are activated by clicking buttons in a toolbar, rather than by holding Shift which seemed to cause problems on Windows).
https://github.com/user-attachments/assets/abc6278b-c24c-4fa9-be3b-5d0ddb462b18

Add polygon draw mode; don't require holding Shift to draw bbox

---

src/config/filters.json

Closes https://github.com/OSMCha/osmcha-frontend/issues/814
The current wording is not how the UI works. There is no network request when typing nor anything else happening … until one presses tab to conclude typing the name.

Wording: Fix user filter description

---

package.json
yarn.lock

Bump maplibre-adiff-viewer to v1.3.1

---

CHANGELOG.md
package.json

Bump version to 1.2.7
